// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-urJBJRBgZszmqMKh_E_FyUc17Y47tSw',
    appId: '1:312607385376:web:743803173e4a6ec72b5945',
    messagingSenderId: '312607385376',
    projectId: 'diary-app-1a621',
    authDomain: 'diary-app-1a621.firebaseapp.com',
    storageBucket: 'diary-app-1a621.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7bSnLFeSqIrCMAeExnSMmOK2sa17sa1o',
    appId: '1:312607385376:android:a3be3b68b98caaf12b5945',
    messagingSenderId: '312607385376',
    projectId: 'diary-app-1a621',
    storageBucket: 'diary-app-1a621.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc62vkqT_p8riWXGWx8xCzDMMTnJ2Vo9w',
    appId: '1:312607385376:ios:24bf98512626d2c82b5945',
    messagingSenderId: '312607385376',
    projectId: 'diary-app-1a621',
    storageBucket: 'diary-app-1a621.firebasestorage.app',
    iosClientId: '312607385376-22t6nrpks56j763jdaiqjvnjv448n6lh.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc62vkqT_p8riWXGWx8xCzDMMTnJ2Vo9w',
    appId: '1:312607385376:ios:24bf98512626d2c82b5945',
    messagingSenderId: '312607385376',
    projectId: 'diary-app-1a621',
    storageBucket: 'diary-app-1a621.firebasestorage.app',
    iosClientId: '312607385376-22t6nrpks56j763jdaiqjvnjv448n6lh.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-urJBJRBgZszmqMKh_E_FyUc17Y47tSw',
    appId: '1:312607385376:web:220e333aeb33df1a2b5945',
    messagingSenderId: '312607385376',
    projectId: 'diary-app-1a621',
    authDomain: 'diary-app-1a621.firebaseapp.com',
    storageBucket: 'diary-app-1a621.firebasestorage.app',
  );

}